# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        #[12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      #using npm ci is generally faster than running npm install
      run: |
        cd my-app
        npm ci
    - name: Build the app
      run: |
        cd my-app
        npm run build
    - name: Run component tests
      run: |
        cd my-app
        npm run test
    - name: Start the app
      run: |
        cd my-app
        npm start &
        npx wait-on --timeout 60000
      
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
